# Generated by Django 5.0 on 2026-04-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("boss", "Boshliq"),
                    ("admin", "Admin"),
                    ("worker", "Ishchi"),
                    ("viewer", "Kuzatuvchi"),
                ],
                default="worker",
                max_length=50,
            ),
        ),
    ]
