# Generated by Django 5.0 on 2026-04-26 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="paid_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="password",
            field=models.CharField(
                default=12345678,
                max_length=16,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
            preserve_default=False,
        ),
    ]
