# Generated by Django 5.0 on 2026-04-26 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderauditlog",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employeekpi",
            name="bonus_kpi",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(1000)],
            ),
        ),
        migrations.AlterField(
            model_name="employeekpi",
            name="salary",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(100000)],
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="closing_cash",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(1000)],
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="opening_cash",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(1000)],
            ),
        ),
    ]
