# Generated by Django 5.2.13 on 2026-04-13 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.restaurant'),
        ),
        migrations.AddField(
            model_name='waste',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wastes', to='orders.menuitem'),
        ),
        migrations.AddField(
            model_name='waste',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wastes', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='waste',
            name='responsible_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guilty', to='users.profile'),
        ),
        migrations.AddField(
            model_name='waste',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.restaurant'),
        ),
    ]
