# Generated by Django 5.0 on 2026-04-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_menuitem_price_alter_order_total_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
