# Generated by Django 5.0 on 2026-04-26 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_menuitem_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="quantity",
        ),
    ]
